# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TTKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for TTKitDemo
   use_frameworks!
    pod 'YYModel'
    pod 'AFNetworking'
    pod 'SDWebImage'

end
