# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'




pod 'Masonry'  #TTControllerCategory

pod 'BaiduMapAPI'
pod 'AliPay'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/SMS'
pod 'UMengUShare/Social/TencentWeibo'


target 'TTSourceDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TTSourceDemo
  
end

